import type { AppInfo } from '@/types';

export const MOCK_APPS: AppInfo[] = [
  {
    folderName: 'dating-quiz',
    packageName: '@barreleye/dating-quiz',
    version: '0.1.2',
    description: '이상형 조건을 발주서처럼 작성하는 테스트 미니앱',
    dependencies: {
      '@apps-in-toss/web-framework': '^2.0.5',
      '@tanstack/react-query': '^5.62.0',
      '@toss/tds-mobile': '^2.0.0',
      react: '^18.3.1',
    },
    granite: {
      appName: 'dating-quiz',
      displayName: '소개팅 발주서',
      primaryColor: '#FF6B6B',
      icon: null,
    },
    console: {
      version: 1,
      nameKo: '소개팅 발주서',
      nameEn: 'Dating Order Form',
      isGame: false,
      aitCategory: '생활 > 콘텐츠 > 테스트',
      subtitle: '내 이상형 조건을 발주서처럼 작성해보세요',
      description:
        '소개팅 나가기 전, 내가 원하는 이상형 조건을 발주서 형식으로 정리해보세요. 결과를 친구에게 공유할 수 있어요.',
      keywords: ['소개팅', '이상형', '테스트', '발주서'],
      logoPath: '.meta/assets/logo.png',
      thumbnailPath: '.meta/assets/thumbnail-wide.png',
      screenshotPaths: ['.meta/assets/screenshot-1.png', '.meta/assets/screenshot-2.png'],
      prdPath: 'docs/PRD.md',
      utPath: 'docs/user-test/report.md',
      prdReviewedAt: '2026-04-01T09:00:00Z',
      prdSource: 'generated',
      pipelineProgress: {
        1: { completedAt: '2026-04-01T09:00:00Z', artifacts: { prd: 'docs/PRD.md' } },
        2: { completedAt: '2026-04-01T10:30:00Z' },
        3: { completedAt: '2026-04-02T09:00:00Z' },
        4: { completedAt: '2026-04-02T10:00:00Z' },
        5: { completedAt: '2026-04-05T16:00:00Z' },
        6: { completedAt: '2026-04-08T11:00:00Z' },
      },
      updatedAt: '2026-04-08T11:00:00Z',
    },
    docs: {
      prd: { exists: true, path: 'docs/PRD.md', date: '2026-04-01', autoDetected: true },
      ut: { exists: true, path: 'docs/user-test/report.md', date: '2026-04-08', autoDetected: true },
    },
    completion: 82,
    completionDetail: { layer1: 38, layer2: 28, layer3: 16 },
  },
  {
    folderName: 'sample',
    packageName: '@barreleye/sample',
    version: '0.0.5',
    description: '샘플 토스 미니앱',
    dependencies: {
      '@apps-in-toss/web-framework': '^2.0.5',
      '@tanstack/react-query': '^5.62.0',
      '@toss/tds-mobile': '^2.0.0',
      react: '^18.3.1',
    },
    granite: {
      appName: 'sample-app',
      displayName: '샘플 앱',
      primaryColor: '#0064FF',
      icon: null,
    },
    console: {
      version: 1,
      nameKo: '샘플 앱',
      nameEn: 'Sample App',
      isGame: false,
      aitCategory: '생활 > 콘텐츠 > 테스트',
      subtitle: '토스 미니앱 개발을 시작해보세요',
      description:
        '바릴아이 프레임워크로 만든 첫 번째 미니앱입니다. 다양한 TDS 컴포넌트를 활용해 빠르게 개발할 수 있어요.',
      keywords: ['샘플', '미니앱', '토스'],
      logoPath: null,
      thumbnailPath: null,
      screenshotPaths: [],
      prdPath: 'docs/PRD.md',
      utPath: null,
      prdReviewedAt: null,
      prdSource: 'uploaded',
      pipelineProgress: {
        1: { completedAt: '2026-04-10T09:00:00Z', artifacts: { prd: 'docs/PRD.md' } },
        3: { completedAt: '2026-04-10T09:30:00Z' },
        4: { completedAt: '2026-04-10T10:00:00Z' },
        5: { completedAt: '2026-04-12T15:00:00Z' },
      },
      updatedAt: '2026-04-12T15:00:00Z',
    },
    docs: {
      prd: { exists: true, path: 'docs/PRD.md', date: '2026-04-10', autoDetected: true },
      ut: { exists: false },
    },
    completion: 57,
    completionDetail: { layer1: 27, layer2: 15, layer3: 15 },
  },
  {
    folderName: 'budget-tracker',
    packageName: '@barreleye/budget-tracker',
    version: '0.0.1',
    description: '간편 가계부 미니앱',
    dependencies: {
      '@apps-in-toss/web-framework': '^2.0.5',
      react: '^18.3.1',
    },
    granite: null,
    console: {
      version: 1,
      nameKo: '',
      nameEn: '',
      isGame: false,
      aitCategory: '',
      subtitle: '',
      description: '',
      keywords: [],
      logoPath: null,
      thumbnailPath: null,
      screenshotPaths: [],
      prdPath: null,
      utPath: null,
      prdReviewedAt: null,
      prdSource: null,
      pipelineProgress: {},
      updatedAt: '',
    },
    docs: {
      prd: { exists: false },
      ut: { exists: false },
    },
    completion: 8,
    completionDetail: { layer1: 8, layer2: 0, layer3: 0 },
  },
];
